cadastros/urls.py
from django.urls import path
from .views import ProdutoCreate, ClienteCreate
from .views import ProdutoUpdate, ClienteUpdate
from .views import ProdutoDelete, ClienteDelete
from .views import ProdutoList, ClienteList

urlpatterns = [
    #############URLS PARA CADASTRAR #############
    path('cadastrar-produto/', ProdutoCreate.as_view(), name ='cadastrar-produto'),
    path('cadastrar-cliente/', ClienteCreate.as_view(), name ='cadastrar-cliente'),
    
    #############URLS PARA EDITAR #############
    path('editar/produto/<int:pk>',ProdutoUpdate.as_view(), name ='editar-produto'),
    path('editar/cliente/<int:pk>', ClienteUpdate.as_view(), name ='editar-cliente'),
    
    #############URLS PARA EXCLUIR #############
    
    path('excluir/produto/<int:pk>',ProdutoDelete.as_view(), name ='excluir-produto'),
    path('excluir/cliente/<int:pk>', ClienteDelete.as_view(), name ='excluir-cliente'),
    
    #############URLS PARA LISTAR #############
    
    path('listar/produto/', ProdutoList.as_view(), name ='listar-produto'),
    path('listar/cliente/', ClienteList.as_view(), name ='listar-cliente'),
    ]

paginas/urls.py
from django.urls import path
from .views import IndexView, SobreView

urlpatterns = [
    path('', IndexView.as_view(), name ='index'), #endereço, MinhaView.as_view(), nome da url 
    path('sobre/', SobreView.as_view(), name ='sobre'), 
    ]

progressao/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('paginas.urls')),
    path('', include('cadastros.urls')),
]

cadastros/models.py
from django.db import models
from django import forms
from django.core.exceptions import ValidationError
            
class Produto(models.Model):
    nome_produto = models.CharField("Nome:", max_length=255, blank=False, unique=True) 
    quantidade_produto = models.IntegerField("Quantidade:", blank=False)
    precocompra_produto = models.DecimalField("Preço de compra:", max_digits=6, decimal_places=2)
    precovenda_produto = models.DecimalField("Preço de venda:",max_digits=6, decimal_places=2)
    tipo = models.CharField(max_length=50, default="produto")
    
    
    def __str__(self):
        return "{} ({})UN".format(self.nome_produto, self.quantidade_produto)
    
def validate_cep(cep):
    #Renive caracteres não numericos
    cep = cep.replace('-','')  
    if not cep.isdigit() or len(cep) != 8:
        raise ValidationError("O CEP está incompleto! ") 
 
def validate_cpf(value):
        # Remove caracteres não numéricos
        cpf = value.replace('.', '').replace('-', '')
        if not cpf.isdigit() or len(cpf) != 11:
            raise ValidationError('CPF deve conter 11 dígitos numéricos.')
        if len(set(cpf)) == 1:
            raise ValidationError('CPF inválido')
        soma = 0
        peso = 10
        for i in range(9):
            soma += int(cpf[i]) * peso
            peso -= 1
        resto = soma % 11
        if resto < 2:
            digito_verif1 = 0
        else:
            digito_verif1 = 11 - resto
    
        soma = 0
        peso = 11
        for i in range(10):
            soma += int(cpf[i]) * peso
            peso -= 1
        resto = soma % 11
        if resto < 2:
            digito_verif2 = 0
        else:
            digito_verif2 = 11 - resto
    
        if int(cpf[-2]) != digito_verif1 or int(cpf[-1]) != digito_verif2:
            raise ValidationError('CPF inválido')
        
class Cliente(models.Model):
    id_cliente = models.BigAutoField(primary_key =True)
    nome_cliente = models.CharField("Nome:", max_length=255)
    email_cliente = models.EmailField("Email:", max_length=254)
    cpf = models.CharField("CPF", max_length=14, unique= True, help_text="Informe apenas números", validators=[validate_cpf])
    telefone = models.CharField("Telefone:", max_length=255, blank= True, unique= True)
    cep = models.CharField("CEP:", max_length=9, validators=[validate_cep]) 
    rua= models.CharField(max_length=50)
    numero = models.IntegerField()
    cidade = models.CharField(max_length=255)
    estado = models.CharField(max_length=255)
    data_nasc = models.DateField(verbose_name="Data de nascimento")
    bairro = models.CharField(max_length=255)
    tipo = models.CharField(max_length=50, default="cliente")
    
    def __str__(self):
        return "({}): {}".format(self.id_cliente, self.nome_cliente)
    
    def save(self, *args, **kwargs):
        # Remove a máscara do CPF antes de salvar
        self.cpf = self.cpf.replace('.', '').replace('-', '')
        super().save(*args, **kwargs)
        
        
    def format_cpf(self):
        # Formata o CPF para exibição
        if not self.cpf: 
            return''
        return f'{self.cpf[:3]}.{self.cpf[3:6]}.{self.cpf[6:9]}-{self.cpf[9:]}'
    

    
    

paginas/models.py
from django.db import models

# Create your models here.

cadastros/views.py
from django.views.generic import CreateView, UpdateView, DeleteView, ListView
from .models import Produto, Cliente
from django.urls import reverse_lazy
from django.contrib import messages

class ProdutoCreate(CreateView):
    model = Produto
    fields = ['nome_produto','quantidade_produto', 'precocompra_produto', 'precovenda_produto',]
    template_name = "cadastros/cadproduto.html"
    success_url = reverse_lazy('listar-produto')
    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, "Produto cadastrado com sucesso!")
        return response
   
    
class ClienteCreate(CreateView):
    model = Cliente
    fields = ['nome_cliente','data_nasc', 'cpf', 'email_cliente',
              'telefone','cep', 'estado', 'cidade', 'rua', 'numero', 'bairro']
    template_name = "cadastros/cadcliente.html"
    success_url = reverse_lazy('listar-cliente')
    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, "Cliente cadastrado com sucesso!")
        return response
    
    
    
################## UPDATE VIEW #################

class ProdutoUpdate(UpdateView):
    model = Produto
    fields = ['nome_produto','quantidade_produto', 'precocompra_produto', 'precovenda_produto',]
    template_name = "cadastros/cadproduto.html"
    success_url = reverse_lazy('listar-produto')
    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, "Dados do produto atualizados com sucesso!")
        return response
   
  
    
class ClienteUpdate(UpdateView):
    model = Cliente
    fields = ['nome_cliente','data_nasc', 'cpf', 'email_cliente',
              'telefone','cep', 'estado', 'cidade', 'rua', 'numero']
    template_name = "cadastros/cadcliente.html"
    success_url = reverse_lazy('listar-cliente')
    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, "Dados do cliente atualizados com sucesso!")
        return response        
    
################## DELETE VIEW #################
    
class ProdutoDelete(DeleteView):
    model = Produto
    template_name = "cadastros/form-excluirProduto.html"
    success_url = reverse_lazy('listar-produto')
    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, "Produto deletado com sucesso!")
        return response


    
class ClienteDelete(DeleteView):
    model = Cliente
    template_name = "cadastros/form-excluirCliente.html"
    success_url = reverse_lazy('listar-cliente')
    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, "Cliente deletado com sucesso!")
        return response    
    
    ################## LIST VIEW #################
    
class ProdutoList(ListView):
    model = Produto
    template_name = "cadastros/listas/produto.html"

    
class ClienteList(ListView):
    model = Cliente
    template_name = "cadastros/listas/cliente.html"


    

paginas/views.py
from django.views.generic import TemplateView
from django.shortcuts import render

class IndexView(TemplateView):
    template_name = "paginas/index.html"

class SobreView(TemplateView):
    template_name = "paginas/sobre.html"

cadastros/templates/cadastros/cadcliente.html
{% extends 'paginas/modelo.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}
<title>Cadastro de Cliente</title>
{% endblock %}


{% block Principal %}
<h3>Cadastre um Cliente</h3>
<p class="lead">
    Preencha o formulário abaixo para cadastrar um novo cliente.
</p>

<form method="post" action="" id="cadastroForm">
    {% csrf_token %}
    <div class="form-row align-items-start">
        <div class="form-group col-md-6">
            {{ form.nome_cliente | as_crispy_field }}
        </div>
        <div class="form-group col-md-3">
            {{ form.cpf | as_crispy_field }}
        </div>
        <div class="form-group col-md3">
            {{ form.data_nasc | as_crispy_field }}
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            {{ form.email_cliente | as_crispy_field }}
        </div>
        <div class="form-group col-md-3">
            {{ form.telefone | as_crispy_field }}
        </div>
        <div class="form-group col-md-3">
            {{ form.cep | as_crispy_field }}
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-3">
            {{ form.estado| as_crispy_field }}
        </div>
        <div class="form-group col-md-3">
            {{ form.cidade | as_crispy_field }}
        </div>
        <div class="form-group col-md-3">
            {{ form.bairro | as_crispy_field }}
        </div>
        <div class="form-group col-md-3">
            {{ form.rua | as_crispy_field }}
        </div>
        <div class="form-group col-md-3">
            {{ form.numero | as_crispy_field }}
        </div>
    </div>
    {% if not form.instance.pk %}
    <!-- Se não houver um ID de cliente (ou seja, criando um novo cliente), exibe o botão Limpar -->
    <button class="btn btn-danger" type="reset">
        <img src="{% static 'img/lixo.svg' %}"> Limpar
    </button>
    {% endif %}
    <button class="btn btn-success" type="submit">
        <img src="{% static 'img/enviar.svg' %}">
        {% if form.instance.pk %}
        Atualizar
        {% else %}
        Enviar
        {% endif %}
    </button>
</form>
{% endblock %}

{% block scripts %}
<script src="{% static 'js/jquery.mask.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
<script>
    //Exibindo máscaras para os campos CPF data de nascimento, CEP e telefone
    $(document).ready(function () {
        $('#id_cpf').mask("000.000.000-00", { reverse: true });
        $('#id_data_nasc').mask('00/00/0000');
        $('#id_cep').mask('00000-000');
        var SPMaskBehavior = function (val) {
            return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009'; //Validando a quantidade de digitos do telefone
        },
        spOptions = {
            onKeyPress: function (val, e, field, options) {
                field.mask(SPMaskBehavior.apply({}, arguments), options);
            }
        };
        $('#id_telefone').mask(SPMaskBehavior, spOptions);

        
        // Função para consumir a API do viacep
        $('#id_cep').blur(function () {
            var cep = $(this).val().replace(/\D/g, '');
            if (cep.length !== 8) {
                return;
            }
            $.getJSON('https://viacep.com.br/ws/' + cep + '/json/', function (data) {
                if (!("erro" in data)) {
                    $('#id_estado').val(data.uf);
                    $('#id_cidade').val(data.localidade);
                    $('#id_rua').val(data.logradouro);
                    $('#id_numero').focus();
                    $('#id_bairro').val(data.bairro);
                } else {
                    Swal.fire({
                        title: 'CEP não encontrado',
                        text: 'O CEP informado não foi encontrado, verifique novamente!',
                        icon: 'warning',
                    })
                }                                           
            });
        });

        // Definindo os campos cidade e estado como readonly
        $('#id_cidade').attr('readonly', true);
        $('#id_estado').attr('readonly', true);
    });
</script>
{% endblock %}

cadastros/templates/cadastros/cadproduto.html
{%extends 'paginas/modelo.html' %}
{%load static %}
{% load crispy_forms_tags %}


{% block titulo %}

<title> Cadastros de Produtos</title>
{% endblock %}


{% block Principal %}
<h3> Cadastre um produto aqui</h3>
<p class="lead"> <b>
        Lembre-se de preencher todos os campos obrigatorios! 
    </p></b>
<form method="POST" action="">
        {% csrf_token %}
        <div class="form-row">
            <div class="form-group col-md-3 mb-0">
                <b>  {{ form.nome_produto | as_crispy_field }} </b>
            </div>
            <div class="form-group col-md-1 mb-0">
                <b>  {{ form.quantidade_produto | as_crispy_field }} </b>
            </div>
        </div>
        <br>
        <div class="form-row">
            <div class="form-group col-md-2 mb-0">
                <b> {{ form.precocompra_produto | as_crispy_field }} </b>
            </div>
            <div class="form-group col-md-2 mb-0">
               <b> {{ form.precovenda_produto | as_crispy_field }}</b>
            </div>
        </div>
    
        {% if not form.instance.pk %}
        <!-- Se não houver um ID de Produto (ou seja, criando um novo Produto), exibe o botão Limpar -->
        <button class="btn btn-danger btn-sm form-group mx-sm-1 mb-2" type="reset">
            <img src="{% static 'img/lixo.svg' %}"> Limpar
        </button>
        {% endif %}
    
        <button class="btn btn-success btn-sm form-group mx-sm-1 mb-2" type="submit">
            <img src="{% static 'img/enviar.svg' %}">
            {% if form.instance.pk %}
            Atualizar
            {% else %}
            Enviar
            {% endif %}
        </button>
    </form>
    

{% endblock %}


{%block scripts %}
<script src="{% static 'js/jquery.mask.min.js' %}"> </script>

<script>//Colocando máscaras no preço de compra e venda
        $(document).ready(function () {
                $('#id_precocompra_produto').mask("#####.00", { reverse: true }); 

                $('#id_precovenda_produto').mask("#####.00", { reverse: true });


        });
</script>
{% endblock %}

cadastros/templates/cadastros/form-excluirCliente.html
{% extends 'paginas/modelo.html' %}
{% load static %}

{% block titulo %}
<title> Excluir Registro</title>
{% endblock %}



{% block Principal %}
<h3>
    Excluir registro
</h3>

<p class="lead">
    Os dados excluídos não podem ser recuperados
</p>

<form id="delete-form1" action="{% url 'excluir-cliente' object.pk %}" method="post">
    {% csrf_token %}
    <p>
        Deseja mesmo excluir o : <b>{{ object}}</b>?
    </p>

    <button type="button" id="confirm-delete-btn" class="btn btn-danger btn-sm form-group mx-sm-1 mb-2">
        <img src="{% static 'img/lixo.svg' %}">Excluir
    </button>

</form>
{% endblock %}

{% block scripts %}
<script>
    document.addEventListener('DOMContentLoaded', function () {
        document.getElementById('confirm-delete-btn').addEventListener('click', function (e) {
            e.preventDefault();
            Swal.fire({
                title: 'Tem certeza?',
                text: 'O registro será excluído permanentemente!',
                icon: 'warning',
                showCancelButton: true,
                cancelButtonText: 'Cancelar',
                confirmButtonText: 'Excluir',
                reverseButton: true,
                confirmButtonColor: 'red'
            }).then((result) => {
                if (result.isConfirmed) {
                    // Enviar o formulário para excluir o cliente
                    document.getElementById('delete-form1').submit();
                }
            });
        });
    });
</script>
{% endblock %}

cadastros/templates/cadastros/form-excluirProduto.html
{% extends 'paginas/modelo.html' %}
{% load static %}

{% block titulo %}
<title> Excluir Registro</title>
{% endblock %}

{% block Principal %}
<h3>
    Excluir registro
</h3>

<p class="lead">
    Os dados excluídos não podem ser recuperados
</p>

<form id="delete-form" action="{% url 'excluir-produto' object.pk %}" method="post">
    {% csrf_token %}
    <p>
        Deseja mesmo excluir o : <b>{{ object}}</b>?
    </p>

    <button type="button" id="confirm-delete-btn" class="btn btn-danger btn-sm form-group mx-sm-1 mb-2">
        <img src="{% static 'img/lixo.svg' %}">Excluir
    </button>

</form>
{% endblock %}

{% block scripts %}
<script>
    document.addEventListener('DOMContentLoaded', function () {
        document.getElementById('confirm-delete-btn').addEventListener('click', function (e) {
            e.preventDefault();
            Swal.fire({
                title: 'Tem certeza?',
                text: 'O registro será excluído permanentemente!',
                icon: 'warning',
                showCancelButton: true,
                cancelButtonText: 'Cancelar',
                confirmButtonText: 'Excluir',
                reverseButton: true,
                confirmButtonColor: 'red'
            }).then((result) => {
                if (result.isConfirmed) {
                    // Enviar o formulário para excluir o produto
                    document.getElementById('delete-form').submit();
                }
            });
        });
    });
</script>
{% endblock %}

cadastros/templates/cadastros/listas/cliente.html
{% extends 'paginas/modelo.html' %}

{% load static %}

{% block titulo %}
<title>Clientes Cadastrados</title>
{% endblock %}


{% block Principal %}
<div class="table-responsive">
    <h3>Clientes cadastrados: </h3>
    <hr>
    <table class="table table-striped table-bordered" id="tabela-cliente">
        <thead>
            <tr style="background-color:#bdbebf">
                <th>Nome</th>
                <th>CPF</th>
                <th>Telefone</th>
                <th>Opções</th>
            </tr>
        </thead>
        <tbody>
            {% for clientes in object_list %}
            <tr>
                <td>{{ clientes.nome_cliente }}</td>
                <td>{{ clientes.format_cpf }}</td>
                <td>{{ clientes.telefone }}</td>
                <td>
                    <a href="{% url 'excluir-cliente' clientes.pk %}"
                        class="btn btn-danger btn-sm form-group mx-sm-1 mb-2" title="Excluir">
                        <img src="{% static 'img/lixo.svg' %}">
                    </a>
                    <a href="{% url 'editar-cliente' clientes.pk %}"
                        class="btn btn-primary btn-sm form-group mx-sm-1 mb-2" title="Editar">
                        <img src="{% static 'img/editar.svg' %}">
                    </a>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="4">Nenhum Cliente registrado.</td>
            </tr>
            {% endfor %}
        </tbody>
        <tfoot>
            <tr>
                <td colspan="2" style="text-align: right; background-color:#bdbebf;">
                    <strong>Total:</strong>
                </td>
                <td style="background-color:#bdbebf">{{ object_list|length }}</td>
            </tr>
        </tfoot>
    </table>
</div>
<div class="text-right mt-3">
    <button id="btn-pdf" class="btn btn-secondary mx-1 mb-2" title="Exportar para PDF"><i class="fas fa-file-pdf"></i>
        PDF</button>
    <button id="btn-excel" class="btn btn-secondary mx-1 mb-2" title="Exportar para Excel"><i
            class="fas fa-file-excel"></i> Excel</button>
</div>
{% block scripts %}
<script>
    $(document).ready(function () {
        var table = $('#tabela-cliente').DataTable({
            responsive: true,
            "aaSorting": [],
            "pageLength": 5,
            "lengthMenu": [[5, 10, 25, 50, -1], [5, 10, 25, 50, "Todos"]],
            "language": {
                "decimal": "",
                "emptyTable": "Sem dados disponíveis",
                "info": "Mostrando _START_ até _END_ de _TOTAL_ registros",
                "infoEmpty": "Mostrando de 0 até 0 de 0 registros",
                "infoFiltered": "(filtrado de _MAX_ registros no total)",
                "infoPostFix": "",
                "thousands": ",",
                "lengthMenu": "Mostrar _MENU_ Clientes",
                "loadingRecords": "Carregando dados...",
                "processing": "Processando...",
                "search": "Procurar:",
                "zeroRecords": "Não foram encontrados resultados",
                "paginate": {
                    "first": "Primeiro",
                    "last": "Último",
                    "next": "Seguinte",
                    "previous": "Anterior"
                },
                "aria": {
                    "sortAscending": ": ordem crescente",
                    "sortDescending": ": ordem decrescente"
                }
            },
            buttons: [
                {
                    extend: 'pdf',
                    className: 'buttons-pdf',
                    titleAttr: 'Exportar para PDF',
                    exportOptions: {
                        columns: [0, 1, 2]
                    }
                }, {
                    extend: 'excel',
                    className: 'buttons-excel',
                    titleAttr: 'Exportar para Excel',
                    exportOptions: {
                        columns: [0, 1, 2]
                    }
                }
            ]
        });

        // Configuração dos botões de exportação
        $('#btn-pdf').on('click', function () {
            table.button('.buttons-pdf').trigger();
        });

        $('#btn-excel').on('click', function () {
            table.button('.buttons-excel').trigger();
        });
    });
</script>
{% endblock %}
{% endblock %}

cadastros/templates/cadastros/listas/produto.html
{% extends 'paginas/modelo.html' %}

{%load static %}

{% block titulo %}

<title>Produtos Cadastrados</title>

{% endblock %}


{%block Principal %}
<div class="table-responsive" >
    <h3>Produtos cadastrados: </h3>
    <hr>
    <table class="table table-striped table-bordered" id="tabela-produto">
        <thead>

            <tr class="table-info">
                <th>Produto</th>
                <th>Quantidade</th>
                <th> Preço de Venda</th>
                <th>Opções</th>
            </tr>
        </thead>
        <tbody>
            {% for produto in object_list %}
            <tr>
                <td> {{ produto.nome_produto }}</td>
                <td> {{ produto.quantidade_produto }} </td>
                <td> {{ produto.precovenda_produto }}</td>
                <td>
                    <a href="{% url 'excluir-produto' produto.pk %}"
                        class="btn btn-danger btn-sm form-group mx-sm-1 mb-2" title="Excluir"><img
                            src="{% static 'img/lixo.svg' %}"></a>
                    <a href="{% url 'editar-produto' produto.pk %}"
                        class="btn btn-primary btn-sm form-group mx-sm-1 mb-2" title="Editar"><img
                            src="{% static 'img/editar.svg' %}"></a>
                </td>

            </tr>

            {% empty %}
            <tr>
                <td colspan="4"> Nenhum produto registrado.</td>
            </tr>


            {% endfor %}
        </tbody>
        <tfoot>
            <tr>
                <td colspan="2" style="text-align: right;"><strong>Total:</strong></td>
                <td>{{ object_list|length }}</td> 
            </tr>
        </tfoot>
    </table>
</div>
<div class="text-right mt-3">
    <button id="btn-pdf" class="btn btn-secondary mx-1 mb-2" title="Exportar para PDF"><i class="fas fa-file-pdf"></i> PDF</button>
    <button id="btn-excel" class="btn btn-secondary mx-1 mb-2" title="Exportar para Excel"><i class="fas fa-file-excel"></i> Excel</button>
</div>
{% block scripts %}
<script>
 $(document).ready(function() { //Usando a API DataTable para deixar mais bonito a exibição dos produtos, também permitindo gerar em PDF E EXCEL os dados
        var table = $('#tabela-produto').DataTable({
            responsive: true,
            "aaSorting": [],
            "pageLength": 5,
            "lengthMenu": [[5, 10, 25, 50, -1], [5, 10, 25, 50, "Todos"]],
            "language": {
                "decimal": "",
                "emptyTable": "Sem dados disponíveis",
                "info": "Mostrando _START_ até _END_ de _TOTAL_ registros",
                "infoEmpty": "Mostrando de 0 até 0 de 0 registros",
                "infoFiltered": "(filtrado de _MAX_ registros no total)",
                "infoPostFix": "",
                "thousands": ",",
                "lengthMenu": "Mostrar _MENU_ Clientes",
                "loadingRecords": "Carregando dados...",
                "processing": "Processando...",
                "search": "Procurar:",
                "zeroRecords": "Não foram encontrados resultados",
                "paginate": {
                    "first": "Primeiro",
                    "last": "Último",
                    "next": "Seguinte",
                    "previous": "Anterior"
                },
                "aria": {
                    "sortAscending": ": ordem crescente",
                    "sortDescending": ": ordem decrescente"
                }
            },
            buttons: [
                 {
                    extend: 'pdf',
                    className: 'buttons-pdf',
                    titleAttr: 'Exportar para PDF',
                    exportOptions: {
                        columns: [0, 1, 2] 
                    }
                }, {
                    extend: 'excel',
                    className: 'buttons-excel',
                    titleAttr: 'Exportar para Excel',
                    exportOptions: {
                        columns: [0, 1, 2] 
                    }
                }
            ]
        });
        
        // Configuração dos botões de exportação PDF E EXCEL
        $('#btn-pdf').on('click', function() {
            table.button('.buttons-pdf').trigger();
        });
        
        $('#btn-excel').on('click', function() {
            table.button('.buttons-excel').trigger();
        });
    });
</script>
{% endblock %}
{% endblock %}

paginas/templates/paginas/index.html
{%extends 'paginas/modelo.html' %}
{% block titulo %}

<title> Página Inicial</title>
{% endblock %}


{%block scripts %}
{% endblock %}

paginas/templates/paginas/sobre.html
{% extends 'paginas/modelo.html' %}

{% block titulo %}

<title> Sobre meu Projeto</title>

{% endblock %}

{% block destaque %}
{%endblock %}

{% block Principal %}

<div class="container d-flex justify-content-center" id="container-home">
    <div class="border border-dark align-self-center" id="div-home">
    <h1>O que será feito?</h1>

    <p>Esta pagina irá possuir um projeto sobre CRUD</p>
</div> 
</div>

{% endblock %}

{%block scripts %}
{% endblock %}